In [ ]:
import IPython.display as ipd
import librosa
import librosa.display

Importing the Sound Dataset

In [ ]:
import glob
a = (glob.glob("/content/drive/MyDrive/Sound/SD_2/*.wav"))  

Storing the labels

In [ ]:
label = []
for i in a:
  temp = []
  temp = (i.split('_')[3].split('.')[0])
  label.append(temp)
  


In [ ]:
test = a[0]

In [ ]:
test

'/content/drive/MyDrive/Sound/SD_2/YAF_gun_ps.wav'

In [ ]:
for i in range(len(label)):
  if (label[i] == 'ps'):
    label[i] = 'surprised'

In [ ]:
from collections import Counter


In [ ]:
Counter(label)

Counter({'angry': 400,
         'disgust': 400,
         'fear': 400,
         'happy': 400,
         'neutral': 400,
         'sad': 400,
         'surprised': 400})

Creating a function to extract features of sound data using Librosa library

In [ ]:
def features_extractor(file):
    audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast') 
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    
    return mfccs_scaled_features

In [ ]:
audio_dataset_path='/content/drive/MyDrive/Sound/SD_2'


Now we iterate through every audio file and extract features using Mel-Frequency Cepstral Coefficients


In [ ]:
import numpy as np
from tqdm import tqdm

extracted_features=[]
for i in tqdm(a):
    file_name = i
    final_class_labels=(i.split('_')[3].split('.')[0])
    data=features_extractor(file_name)
    extracted_features.append([data,final_class_labels])

100%|██████████| 2800/2800 [15:21<00:00,  3.04it/s]


In [ ]:
import warnings
warnings.filterwarnings("ignore")

Converting extracted_features to Pandas dataframe


In [ ]:
extracted_features_df=pd.DataFrame(extracted_features,columns=['feature','class'])
extracted_features_df.head()

feature  class
0  [-355.69376, 57.323643, -23.254953, 5.7955832,...     ps
1  [-323.7222, 29.46084, -28.330841, 12.185203, -...  angry
2  [-300.7868, 37.027794, -19.649448, 40.014153, ...   fear
3  [-334.66147, 44.841854, -40.6202, 3.5719078, -...     ps
4  [-311.78323, 43.74869, -30.711937, 18.918646, ...   fear

In [ ]:
extracted_features_df.replace(to_replace ="ps",
                 value ="surprised")

feature      class
0     [-355.69376, 57.323643, -23.254953, 5.7955832,...  surprised
1     [-323.7222, 29.46084, -28.330841, 12.185203, -...      angry
2     [-300.7868, 37.027794, -19.649448, 40.014153, ...       fear
3     [-334.66147, 44.841854, -40.6202, 3.5719078, -...  surprised
4     [-311.78323, 43.74869, -30.711937, 18.918646, ...       fear
...                                                 ...        ...
2795  [-445.30246, 71.04448, 7.4023705, -3.6404228, ...       fear
2796  [-464.97357, 87.857124, 19.857723, 20.849457, ...    disgust
2797  [-502.36795, 75.44127, 8.496121, 20.935692, 11...    disgust
2798  [-413.2373, 74.80348, -9.518274, -5.9231834, -...       fear
2799  [-502.11514, 87.08189, 4.675834, 8.59819, 8.18...    neutral

[2800 rows x 2 columns]

 Split the dataset into independent and dependent dataset


In [ ]:
X=np.array(extracted_features_df['feature'].tolist())
y=np.array(extracted_features_df['class'].tolist())

In [ ]:
X.shape


(2800, 40)

In [ ]:
y

array(['ps', 'angry', 'fear', ..., 'disgust', 'fear', 'neutral'],
      dtype='<U7')

In [ ]:
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
y=to_categorical(labelencoder.fit_transform(y))

In [ ]:
y

array([[0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
X_train

array([[-5.2566028e+02,  8.8053703e+01,  1.7790604e+01, ...,
         1.3830474e+01,  1.0719818e+01,  1.5248736e+01],
       [-3.0149756e+02,  3.2979958e+01, -2.5914604e+01, ...,
        -6.3365617e+00, -4.5419664e+00, -3.0858165e-01],
       [-3.3398419e+02,  1.5430432e+01, -1.6283096e+01, ...,
        -2.3440795e+00, -2.5255470e+00, -1.8828529e-01],
       ...,
       [-3.8382471e+02,  6.1429348e+01, -2.5949579e+01, ...,
         1.6181866e+00,  3.8618839e+00, -1.0109454e+00],
       [-4.1996460e+02,  8.9124176e+01,  7.5640635e+00, ...,
         9.7622547e+00,  6.9978070e+00,  5.1651907e+00],
       [-4.5130487e+02,  9.7292252e+01,  2.3432587e+01, ...,
         5.0757513e+00,  4.5313263e+00,  4.2487245e+00]], dtype=float32)

In [ ]:
y

array([[0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [ ]:
X_train.shape


(2240, 40)

In [ ]:
X_test.shape


(560, 40)

In [ ]:
y_train.shape


(2240, 7)

In [ ]:
y_test.shape


(560, 7)

Creating my Model 

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten
from tensorflow.keras.optimizers import Adam
from sklearn import metrics

In [ ]:
### No of classes
num_labels=y.shape[1]

In [ ]:
model=Sequential()
###first layer
model.add(Dense(100,input_shape=(40,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###second layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###third layer
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))

###final layer
model.add(Dense(num_labels))
model.add(Activation('softmax'))

In [ ]:
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               4100      
_________________________________________________________________
activation (Activation)      (None, 100)               0         
_________________________________________________________________
dropout (Dropout)            (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 200)               20200     
_________________________________________________________________
activation_1 (Activation)    (None, 200)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 100)               2

In [ ]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')


Training my model

In [ ]:

from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime 

num_epochs = 100
num_batch_size = 32

checkpointer = ModelCheckpoint(filepath='saved_models/audio_classification.hdf5', 
                               verbose=1, save_best_only=True)
start = datetime.now()

model.fit(X_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(X_test, y_test), callbacks=[checkpointer], verbose=1)


duration = datetime.now() - start
print("Training completed in time: ", duration)

Epoch 1/100
70/70 [==============================] - 1s 6ms/step - loss: 28.5737 - accuracy: 0.1437 - val_loss: 1.9373 - val_accuracy: 0.2357

Epoch 00001: val_loss improved from inf to 1.93730, saving model to saved_models/audio_classification.hdf5
Epoch 2/100
70/70 [==============================] - 0s 3ms/step - loss: 5.7380 - accuracy: 0.1576 - val_loss: 1.9442 - val_accuracy: 0.1554

Epoch 00002: val_loss did not improve from 1.93730
Epoch 3/100
70/70 [==============================] - 0s 3ms/step - loss: 2.8841 - accuracy: 0.1598 - val_loss: 1.9439 - val_accuracy: 0.1554

Epoch 00003: val_loss did not improve from 1.93730
Epoch 4/100
70/70 [==============================] - 0s 4ms/step - loss: 2.3401 - accuracy: 0.1469 - val_loss: 1.9439 - val_accuracy: 0.1554

Epoch 00004: val_loss did not improve from 1.93730
Epoch 5/100
70/70 [==============================] - 0s 4ms/step - loss: 2.1115 - accuracy: 0.1576 - val_loss: 1.9443 - val_accuracy: 0.1554

Epoch 00005: val_loss did not

Result : Accuracy -> 98.93%

In [ ]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

0.9892857074737549
